#!/bin/bash
# NOTE: Despite the .cmd suffix, this is a Bash SLURM submission script.
#SBATCH --output=log/test_%j.out
#SBATCH --error=log/test_%j.err
#SBATCH --time=2:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16g
#SBATCH --job-name=ROCE_test
#SBATCH -p preempt,saffo-2tb,msismall,msilarge,msilong,amdsmall,agsmall,amdlarge,amd512,amd2tb
#SBATCH --nice=5

# ============================================================================
# RoCE Test / Build SLURM Batch Script
# ============================================================================
# Paired with test.sh; invoked via sbatch with --export carrying:
#   COMPILE_ONLY   TRUE|FALSE (default FALSE) — skip the test suite
#   TEST_FILTER    regex passed to testthat::test_local(filter=) (may be empty)
#   TEST_REPORTER  testthat reporter name (default: summary)
#   USE_INSTALLED  TRUE|FALSE (default FALSE) — test against installed RoCE
#                  without reinstalling it first
#   USE_SOURCE     TRUE|FALSE (default FALSE) — test source tree via
#                  devtools::load_all() without reinstalling first
# ============================================================================

# Change directory to project directory (where sbatch was invoked)
cd "${SLURM_SUBMIT_DIR:-$(dirname "$0")}"

# Load the environment file generated by test.sh. This avoids Slurm --export
# comma parsing problems for diagnostic variables such as ROCE_*_P=10,50.
if [[ -n "${ROCE_TEST_ENV_FILE:-}" ]]; then
    if [[ -f "${ROCE_TEST_ENV_FILE}" ]]; then
        # shellcheck source=/dev/null
        source "${ROCE_TEST_ENV_FILE}"
    else
        echo "ROCE_TEST_ENV_FILE was set but not found: ${ROCE_TEST_ENV_FILE}"
        exit 1
    fi
fi

# Load R module
# Pin to the spack/centos7-ivybridge build that RoCE.so is compiled against;
# unqualified `module load R` can resolve to a different build on Rocky 8 nodes.
module load R/4.2.2-gcc-8.2.0-vp7tyde

# Override unconditionally: the spack `R/4.2.2-gcc-8.2.0-vp7tyde` module sets
# its own R_LIBS_USER (~/R/library), which is empty on this account. All 270
# installed packages — including RoCE's compile-time deps Rcpp, RcppEigen,
# glmnet, doParallel — live in ~/Rlibs, so we force that path.
export R_LIBS_USER="${HOME}/Rlibs"

# Prevent BLAS/OpenMP oversubscription during compilation and tests
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export BLIS_NUM_THREADS=1

# ============================================================================
# Parameters (exported by test.sh)
# ============================================================================
COMPILE_ONLY="${COMPILE_ONLY:-false}"
TEST_FILTER="${TEST_FILTER:-}"
TEST_REPORTER="${TEST_REPORTER:-summary}"
USE_INSTALLED="${USE_INSTALLED:-false}"
USE_SOURCE="${USE_SOURCE:-false}"

# Honour the test helper's switch between load_all and installed package
if [[ "${USE_INSTALLED}" == "true" || "${USE_INSTALLED}" == "TRUE" ]]; then
    export ROCE_TEST_INSTALLED=1
else
    unset ROCE_TEST_INSTALLED
fi

mkdir -p log

echo "=============================================="
echo "RoCE Test / Build Job"
echo "=============================================="
echo "Job ID:        ${SLURM_JOB_ID}"
echo "Mode:          $([[ "${COMPILE_ONLY}" == "true" ]] && echo "compile only" || echo "build + test")"
echo "Test filter:   ${TEST_FILTER:-<none>}"
echo "Test reporter: ${TEST_REPORTER}"
echo "Use installed: ${USE_INSTALLED}"
echo "Use source:    ${USE_SOURCE}"
echo "Start time:    $(date)"
echo "=============================================="

# ============================================================================
# 1. Build the package (triggers C++ compilation via Rcpp)
# ============================================================================
SHOULD_INSTALL=true
if [[ "${USE_INSTALLED}" == "true" || "${USE_INSTALLED}" == "TRUE" ]]; then
    SHOULD_INSTALL=false
fi
if [[ "${USE_SOURCE}" == "true" || "${USE_SOURCE}" == "TRUE" ]]; then
    SHOULD_INSTALL=false
fi

if [[ "${COMPILE_ONLY}" == "true" || "${COMPILE_ONLY}" == "TRUE" ]]; then
    SHOULD_INSTALL=true
fi

if [[ "${SHOULD_INSTALL}" == "true" ]]; then
    echo ""
    echo "[$(date)] Building RoCE package (R CMD INSTALL --preclean)"
    # -l explicitly targets ~/Rlibs so the install lands where everything else
    # is and R CMD INSTALL can resolve Rcpp/RcppEigen/glmnet/doParallel.
    if R CMD INSTALL --preclean --no-docs --no-help --no-demo -l "${R_LIBS_USER}" .; then
        echo "[$(date)] Build succeeded."
    else
        INSTALL_EXIT=$?
        echo "[$(date)] R CMD INSTALL failed with exit code ${INSTALL_EXIT}"
        exit ${INSTALL_EXIT}
    fi
else
    echo ""
    if [[ "${USE_SOURCE}" == "true" || "${USE_SOURCE}" == "TRUE" ]]; then
        echo "[$(date)] USE_SOURCE=true; skipping R CMD INSTALL and testing source tree via devtools::load_all()"
    else
        echo "[$(date)] USE_INSTALLED=true; skipping R CMD INSTALL and using existing RoCE from R_LIBS_USER=${R_LIBS_USER}"
    fi
fi

if [[ "${COMPILE_ONLY}" == "true" ]]; then
    echo ""
    echo "=============================================="
    echo "Compile-only run complete at: $(date)"
    echo "=============================================="
    exit 0
fi

# ============================================================================
# 2. Run the testthat suite
# ============================================================================
echo ""
echo "[$(date)] Running testthat test suite"

# Rscript invocation constructs the filter/reporter arguments from env vars.
# Using testthat::test_local() is consistent with tests/testthat/helper-load.R,
# which prefers devtools::load_all() against the source tree unless
# ROCE_TEST_INSTALLED is set.
Rscript - <<'RSCRIPT'
suppressPackageStartupMessages({
    if (!requireNamespace("testthat", quietly = TRUE)) {
        stop("testthat is required to run the RoCE test suite")
    }
})

test_filter   <- Sys.getenv("TEST_FILTER", "")
test_reporter <- Sys.getenv("TEST_REPORTER", "summary")

# stop_on_failure=TRUE: testthat runs the full suite, prints the summary, and
# raises at the end if any expectation failed or any test errored out. With
# Rscript, that raised error propagates as a non-zero exit code, which SLURM
# reports as job failure; silent passes leave exit 0.
# The summary reporter prints only its first ten failures by default; show all.
options(testthat.summary.max_reports = 1000L)
args <- list(reporter = test_reporter, stop_on_failure = TRUE)
if (nzchar(test_filter)) args$filter <- test_filter

cat(sprintf("[R] testthat::test_local(filter = %s, reporter = %s)\n",
            if (nzchar(test_filter)) shQuote(test_filter) else "NULL",
            shQuote(test_reporter)))

do.call(testthat::test_local, args)
cat("[R] All tests passed.\n")
RSCRIPT

TEST_EXIT=$?

echo ""
echo "=============================================="
echo "Test job completed at: $(date)"
echo "Exit code: ${TEST_EXIT}"
echo "=============================================="

exit ${TEST_EXIT}
