#!/usr/bin/env python3
"""Extract local method-reference PDFs into docs/*.extracted.txt.

The script is intentionally dependency-tolerant:
1. Try pypdf/PyPDF2/pdfminer.six when available.
2. Fall back to Ghostscript txtwrite.
3. Fall back to `strings` only as a last-resort diagnostic text source.

It does not download anything and only writes the requested extracted text files.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


DEFAULT_PDFS = ("FACE.pdf", "SMMAL.pdf")


def extract_with_pypdf(pdf_path: Path) -> str:
    try:
        import pypdf  # type: ignore
    except Exception:
        pypdf = None
    if pypdf is not None:
        reader = pypdf.PdfReader(str(pdf_path))
        return "\n".join(page.extract_text() or "" for page in reader.pages)

    try:
        import PyPDF2  # type: ignore
    except Exception:
        return ""
    reader = PyPDF2.PdfReader(str(pdf_path))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def extract_with_pdfminer(pdf_path: Path) -> str:
    try:
        from pdfminer.high_level import extract_text  # type: ignore
    except Exception:
        return ""
    return extract_text(str(pdf_path)) or ""


def run_command(cmd):
    try:
        completed = subprocess.run(
            cmd,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            errors="replace",
        )
    except Exception:
        return ""
    return completed.stdout


def extract_with_ghostscript(pdf_path: Path) -> str:
    gs = shutil.which("gs") or ("/usr/bin/gs" if Path("/usr/bin/gs").exists() else "")
    if not gs:
        return ""
    return run_command(
        [
            gs,
            "-q",
            "-dNOPAUSE",
            "-dBATCH",
            "-sDEVICE=txtwrite",
            "-sOutputFile=-",
            str(pdf_path),
        ]
    )


def extract_with_strings(pdf_path: Path) -> str:
    strings = shutil.which("strings") or ("/usr/bin/strings" if Path("/usr/bin/strings").exists() else "")
    if not strings:
        return ""
    return run_command([strings, str(pdf_path)])


def extract_pdf_text(pdf_path):
    methods = (
        ("pypdf/PyPDF2", extract_with_pypdf),
        ("pdfminer.six", extract_with_pdfminer),
        ("ghostscript", extract_with_ghostscript),
        ("strings", extract_with_strings),
    )
    for name, extractor in methods:
        text = extractor(pdf_path)
        if len(text.strip()) >= 200:
            return text, name
    return "", "none"


def sanitize_text(text):
    """Keep extracted PDF text readable for grep/readLines-based audits."""
    return text.replace("\x00", " ").replace("\r", "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", default="docs", help="Directory containing PDFs and receiving text outputs.")
    parser.add_argument("--pdf", action="append", default=[], help="PDF filename under docs-dir. Repeatable.")
    args = parser.parse_args()

    docs_dir = Path(args.docs_dir).resolve()
    pdf_names = args.pdf or list(DEFAULT_PDFS)

    if not docs_dir.exists():
        raise SystemExit(f"docs directory not found: {docs_dir}")

    failures = []
    for pdf_name in pdf_names:
        pdf_path = docs_dir / pdf_name
        if not pdf_path.exists():
            failures.append(f"{pdf_name}: missing")
            continue

        text, method = extract_pdf_text(pdf_path)
        out_path = docs_dir / f"{pdf_path.stem}.extracted.txt"
        if not text.strip():
            failures.append(f"{pdf_name}: extraction failed")
            continue

        text = sanitize_text(text)
        header = (
            f"# Extracted text from {pdf_name}\n"
            f"# Method: {method}\n"
            "# Generated by diagnosis/method_alignment/extract_method_pdfs.py\n\n"
        )
        out_path.write_text(header + text, encoding="utf-8")
        print(f"[pdf-extract] wrote {out_path} using {method} ({len(text)} chars)")

    if failures:
        for failure in failures:
            print(f"[pdf-extract] ERROR {failure}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
