// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RoCE_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nuisance_solver_cpp
std::string nuisance_solver_cpp();
RcppExport SEXP _RoCE_nuisance_solver_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nuisance_solver_cpp());
    return rcpp_result_gen;
END_RCPP
}
// set_nuisance_solver_cpp
std::string set_nuisance_solver_cpp(std::string solver);
RcppExport SEXP _RoCE_set_nuisance_solver_cpp(SEXP solverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type solver(solverSEXP);
    rcpp_result_gen = Rcpp::wrap(set_nuisance_solver_cpp(solver));
    return rcpp_result_gen;
END_RCPP
}
// fit_unified_density_ratio_cpp
List fit_unified_density_ratio_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& mean_grad_psi, const VectorXd& alpha_init, double lambda, int max_iter, double tol, bool calibrated, double M_tau, const MatrixXd& W_outcome, int A_val, int family_int, int link_int, const VectorXd& warm_start, bool truncate_initial_outcome);
RcppExport SEXP _RoCE_fit_unified_density_ratio_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP mean_grad_psiSEXP, SEXP alpha_initSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP calibratedSEXP, SEXP M_tauSEXP, SEXP W_outcomeSEXP, SEXP A_valSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP warm_startSEXP, SEXP truncate_initial_outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mean_grad_psi(mean_grad_psiSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type calibrated(calibratedSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type warm_start(warm_startSEXP);
    Rcpp::traits::input_parameter< bool >::type truncate_initial_outcome(truncate_initial_outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_unified_density_ratio_cpp(Z_site, A_source, mean_grad_psi, alpha_init, lambda, max_iter, tol, calibrated, M_tau, W_outcome, A_val, family_int, link_int, warm_start, truncate_initial_outcome));
    return rcpp_result_gen;
END_RCPP
}
// fit_initial_density_ratio_cpp
List fit_initial_density_ratio_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& mean_phi, double lambda, int max_iter, double tol, int A_val, double M_tau, const VectorXd& warm_start);
RcppExport SEXP _RoCE_fit_initial_density_ratio_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP mean_phiSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP M_tauSEXP, SEXP warm_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mean_phi(mean_phiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type warm_start(warm_startSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_initial_density_ratio_cpp(Z_site, A_source, mean_phi, lambda, max_iter, tol, A_val, M_tau, warm_start));
    return rcpp_result_gen;
END_RCPP
}
// select_lambda_cv_density_ratio_cpp
List select_lambda_cv_density_ratio_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& mean_grad_psi, const VectorXd& alpha_init, const VectorXd& lambda_grid, int n_folds, int max_iter, double tol, int A_val, int family_int, int link_int, Rcpp::Nullable<Rcpp::NumericVector> cv_fold_id, bool use_kkt_certificate);
RcppExport SEXP _RoCE_select_lambda_cv_density_ratio_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP mean_grad_psiSEXP, SEXP alpha_initSEXP, SEXP lambda_gridSEXP, SEXP n_foldsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP cv_fold_idSEXP, SEXP use_kkt_certificateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mean_grad_psi(mean_grad_psiSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cv_fold_id(cv_fold_idSEXP);
    Rcpp::traits::input_parameter< bool >::type use_kkt_certificate(use_kkt_certificateSEXP);
    rcpp_result_gen = Rcpp::wrap(select_lambda_cv_density_ratio_cpp(Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, A_val, family_int, link_int, cv_fold_id, use_kkt_certificate));
    return rcpp_result_gen;
END_RCPP
}
// select_lambda_cv_initial_density_ratio_cpp
List select_lambda_cv_initial_density_ratio_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& mean_phi, const VectorXd& lambda_grid, int n_folds, int max_iter, double tol, int A_val, double M_tau, Rcpp::Nullable<Rcpp::NumericVector> cv_fold_id, bool use_kkt_certificate);
RcppExport SEXP _RoCE_select_lambda_cv_initial_density_ratio_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP mean_phiSEXP, SEXP lambda_gridSEXP, SEXP n_foldsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP M_tauSEXP, SEXP cv_fold_idSEXP, SEXP use_kkt_certificateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mean_phi(mean_phiSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cv_fold_id(cv_fold_idSEXP);
    Rcpp::traits::input_parameter< bool >::type use_kkt_certificate(use_kkt_certificateSEXP);
    rcpp_result_gen = Rcpp::wrap(select_lambda_cv_initial_density_ratio_cpp(Z_site, A_source, mean_phi, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, cv_fold_id, use_kkt_certificate));
    return rcpp_result_gen;
END_RCPP
}
// select_lambda_cv_calibrated_density_ratio_cpp
List select_lambda_cv_calibrated_density_ratio_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& mean_grad_psi, const VectorXd& alpha_init, const VectorXd& lambda_grid, int n_folds, int max_iter, double tol, double M_tau, const MatrixXd& W_outcome, int A_val, int family_int, int link_int, Rcpp::Nullable<Rcpp::NumericVector> cv_fold_id, bool truncate_initial_outcome, bool use_kkt_certificate);
RcppExport SEXP _RoCE_select_lambda_cv_calibrated_density_ratio_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP mean_grad_psiSEXP, SEXP alpha_initSEXP, SEXP lambda_gridSEXP, SEXP n_foldsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP M_tauSEXP, SEXP W_outcomeSEXP, SEXP A_valSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP cv_fold_idSEXP, SEXP truncate_initial_outcomeSEXP, SEXP use_kkt_certificateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mean_grad_psi(mean_grad_psiSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cv_fold_id(cv_fold_idSEXP);
    Rcpp::traits::input_parameter< bool >::type truncate_initial_outcome(truncate_initial_outcomeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_kkt_certificate(use_kkt_certificateSEXP);
    rcpp_result_gen = Rcpp::wrap(select_lambda_cv_calibrated_density_ratio_cpp(Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, M_tau, W_outcome, A_val, family_int, link_int, cv_fold_id, truncate_initial_outcome, use_kkt_certificate));
    return rcpp_result_gen;
END_RCPP
}
// fit_unified_outcome_cpp
List fit_unified_outcome_cpp(const MatrixXd& W_outcome, const VectorXd& Y_source, const VectorXd& A_source, const VectorXd& gamma_s, int family_int, int link_int, double lambda, int max_iter, double tol, int A_val, bool calibrated, double M_tau, const MatrixXd& Z_site, const VectorXd& warm_start, bool use_weight_derivative);
RcppExport SEXP _RoCE_fit_unified_outcome_cpp(SEXP W_outcomeSEXP, SEXP Y_sourceSEXP, SEXP A_sourceSEXP, SEXP gamma_sSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP calibratedSEXP, SEXP M_tauSEXP, SEXP Z_siteSEXP, SEXP warm_startSEXP, SEXP use_weight_derivativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y_source(Y_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type gamma_s(gamma_sSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< bool >::type calibrated(calibratedSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type warm_start(warm_startSEXP);
    Rcpp::traits::input_parameter< bool >::type use_weight_derivative(use_weight_derivativeSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_unified_outcome_cpp(W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda, max_iter, tol, A_val, calibrated, M_tau, Z_site, warm_start, use_weight_derivative));
    return rcpp_result_gen;
END_RCPP
}
// fit_general_glm_cpp
List fit_general_glm_cpp(const MatrixXd& X, const VectorXd& Y, const VectorXd& weights, int family_int, int link_int, double lambda, int max_iter, double tol, const VectorXd& warm_start);
RcppExport SEXP _RoCE_fit_general_glm_cpp(SEXP XSEXP, SEXP YSEXP, SEXP weightsSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP warm_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type warm_start(warm_startSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_general_glm_cpp(X, Y, weights, family_int, link_int, lambda, max_iter, tol, warm_start));
    return rcpp_result_gen;
END_RCPP
}
// select_lambda_cv_general_refined_outcome_cpp
List select_lambda_cv_general_refined_outcome_cpp(const MatrixXd& W_outcome, const VectorXd& Y_source, const VectorXd& A_source, const VectorXd& gamma_s, int family_int, int link_int, const VectorXd& lambda_grid, int n_folds, int max_iter, double tol, int A_val, const MatrixXd& Z_site, Rcpp::Nullable<Rcpp::NumericVector> cv_fold_id);
RcppExport SEXP _RoCE_select_lambda_cv_general_refined_outcome_cpp(SEXP W_outcomeSEXP, SEXP Y_sourceSEXP, SEXP A_sourceSEXP, SEXP gamma_sSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP lambda_gridSEXP, SEXP n_foldsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP Z_siteSEXP, SEXP cv_fold_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y_source(Y_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type gamma_s(gamma_sSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cv_fold_id(cv_fold_idSEXP);
    rcpp_result_gen = Rcpp::wrap(select_lambda_cv_general_refined_outcome_cpp(W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda_grid, n_folds, max_iter, tol, A_val, Z_site, cv_fold_id));
    return rcpp_result_gen;
END_RCPP
}
// select_lambda_cv_calibrated_outcome_cpp
List select_lambda_cv_calibrated_outcome_cpp(const MatrixXd& W_outcome, const VectorXd& Y_source, const VectorXd& A_source, const VectorXd& gamma_init, const VectorXd& lambda_grid, int n_folds, int max_iter, double tol, int A_val, double M_tau, const MatrixXd& Z_site, int family_int, int link_int, Rcpp::Nullable<Rcpp::NumericVector> cv_fold_id, bool use_weight_derivative);
RcppExport SEXP _RoCE_select_lambda_cv_calibrated_outcome_cpp(SEXP W_outcomeSEXP, SEXP Y_sourceSEXP, SEXP A_sourceSEXP, SEXP gamma_initSEXP, SEXP lambda_gridSEXP, SEXP n_foldsSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP A_valSEXP, SEXP M_tauSEXP, SEXP Z_siteSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP cv_fold_idSEXP, SEXP use_weight_derivativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y_source(Y_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type n_folds(n_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type cv_fold_id(cv_fold_idSEXP);
    Rcpp::traits::input_parameter< bool >::type use_weight_derivative(use_weight_derivativeSEXP);
    rcpp_result_gen = Rcpp::wrap(select_lambda_cv_calibrated_outcome_cpp(W_outcome, Y_source, A_source, gamma_init, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, Z_site, family_int, link_int, cv_fold_id, use_weight_derivative));
    return rcpp_result_gen;
END_RCPP
}
// calculate_glm_gradient_cpp
MatrixXd calculate_glm_gradient_cpp(const MatrixXd& W_outcome, const VectorXd& beta, int family_int, int link_int);
RcppExport SEXP _RoCE_calculate_glm_gradient_cpp(SEXP W_outcomeSEXP, SEXP betaSEXP, SEXP family_intSEXP, SEXP link_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_glm_gradient_cpp(W_outcome, beta, family_int, link_int));
    return rcpp_result_gen;
END_RCPP
}
// mean_glm_gradient_cpp
VectorXd mean_glm_gradient_cpp(const MatrixXd& W_outcome, const VectorXd& beta, int family_int, int link_int);
RcppExport SEXP _RoCE_mean_glm_gradient_cpp(SEXP W_outcomeSEXP, SEXP betaSEXP, SEXP family_intSEXP, SEXP link_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_glm_gradient_cpp(W_outcome, beta, family_int, link_int));
    return rcpp_result_gen;
END_RCPP
}
// predict_glm_cpp
VectorXd predict_glm_cpp(const MatrixXd& W_outcome, const VectorXd& beta, int family_int, int link_int);
RcppExport SEXP _RoCE_predict_glm_cpp(SEXP W_outcomeSEXP, SEXP betaSEXP, SEXP family_intSEXP, SEXP link_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_glm_cpp(W_outcome, beta, family_int, link_int));
    return rcpp_result_gen;
END_RCPP
}
// calculate_correction_term_cpp
List calculate_correction_term_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& Y_source, const VectorXd& gamma_s, const VectorXd& alpha_ts, const MatrixXd& W_outcome, double M_tau, int family_int, int link_int, int A_val);
RcppExport SEXP _RoCE_calculate_correction_term_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP Y_sourceSEXP, SEXP gamma_sSEXP, SEXP alpha_tsSEXP, SEXP W_outcomeSEXP, SEXP M_tauSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP A_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y_source(Y_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type gamma_s(gamma_sSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_ts(alpha_tsSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_correction_term_cpp(Z_site, A_source, Y_source, gamma_s, alpha_ts, W_outcome, M_tau, family_int, link_int, A_val));
    return rcpp_result_gen;
END_RCPP
}
// calculate_source_variance_cpp
List calculate_source_variance_cpp(const MatrixXd& Z_site, const VectorXd& A_source, const VectorXd& Y_source, const VectorXd& gamma_s, const VectorXd& alpha_ts, double delta_ts, const MatrixXd& W_outcome, double M_tau, int family_int, int link_int, int A_val);
RcppExport SEXP _RoCE_calculate_source_variance_cpp(SEXP Z_siteSEXP, SEXP A_sourceSEXP, SEXP Y_sourceSEXP, SEXP gamma_sSEXP, SEXP alpha_tsSEXP, SEXP delta_tsSEXP, SEXP W_outcomeSEXP, SEXP M_tauSEXP, SEXP family_intSEXP, SEXP link_intSEXP, SEXP A_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type Z_site(Z_siteSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type A_source(A_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type Y_source(Y_sourceSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type gamma_s(gamma_sSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_ts(alpha_tsSEXP);
    Rcpp::traits::input_parameter< double >::type delta_ts(delta_tsSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type W_outcome(W_outcomeSEXP);
    Rcpp::traits::input_parameter< double >::type M_tau(M_tauSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    Rcpp::traits::input_parameter< int >::type A_val(A_valSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_source_variance_cpp(Z_site, A_source, Y_source, gamma_s, alpha_ts, delta_ts, W_outcome, M_tau, family_int, link_int, A_val));
    return rcpp_result_gen;
END_RCPP
}
// calculate_target_variance_cpp
List calculate_target_variance_cpp(const MatrixXd& target_W_outcome, const VectorXd& alpha_ts, double M_ts, int family_int, int link_int);
RcppExport SEXP _RoCE_calculate_target_variance_cpp(SEXP target_W_outcomeSEXP, SEXP alpha_tsSEXP, SEXP M_tsSEXP, SEXP family_intSEXP, SEXP link_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const MatrixXd& >::type target_W_outcome(target_W_outcomeSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type alpha_ts(alpha_tsSEXP);
    Rcpp::traits::input_parameter< double >::type M_ts(M_tsSEXP);
    Rcpp::traits::input_parameter< int >::type family_int(family_intSEXP);
    Rcpp::traits::input_parameter< int >::type link_int(link_intSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_target_variance_cpp(target_W_outcome, alpha_ts, M_ts, family_int, link_int));
    return rcpp_result_gen;
END_RCPP
}
// calculate_covariance_term_cpp
double calculate_covariance_term_cpp(const VectorXd& varphi_ot, const VectorXd& zeta_components);
RcppExport SEXP _RoCE_calculate_covariance_term_cpp(SEXP varphi_otSEXP, SEXP zeta_componentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const VectorXd& >::type varphi_ot(varphi_otSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type zeta_components(zeta_componentsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_covariance_term_cpp(varphi_ot, zeta_components));
    return rcpp_result_gen;
END_RCPP
}
// optimize_weights_cpp
List optimize_weights_cpp(const VectorXd& estimates, const VectorXd& V_t, const VectorXd& V_s, const VectorXd& n_s, double V_ot, double n_t, const VectorXd& C_ot, double lambda, double mu_ot, int max_iter, double tol, const MatrixXd& C_cross, const VectorXd& warm_start);
RcppExport SEXP _RoCE_optimize_weights_cpp(SEXP estimatesSEXP, SEXP V_tSEXP, SEXP V_sSEXP, SEXP n_sSEXP, SEXP V_otSEXP, SEXP n_tSEXP, SEXP C_otSEXP, SEXP lambdaSEXP, SEXP mu_otSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP C_crossSEXP, SEXP warm_startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const VectorXd& >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_t(V_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_s(V_sSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< double >::type V_ot(V_otSEXP);
    Rcpp::traits::input_parameter< double >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type C_ot(C_otSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ot(mu_otSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type C_cross(C_crossSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type warm_start(warm_startSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_weights_cpp(estimates, V_t, V_s, n_s, V_ot, n_t, C_ot, lambda, mu_ot, max_iter, tol, C_cross, warm_start));
    return rcpp_result_gen;
END_RCPP
}
// calculate_aggregated_estimate_cpp
double calculate_aggregated_estimate_cpp(double mu_ot, const VectorXd& mu_ts, const VectorXd& eta);
RcppExport SEXP _RoCE_calculate_aggregated_estimate_cpp(SEXP mu_otSEXP, SEXP mu_tsSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_ot(mu_otSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type mu_ts(mu_tsSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_aggregated_estimate_cpp(mu_ot, mu_ts, eta));
    return rcpp_result_gen;
END_RCPP
}
// calculate_aggregated_variance_cpp
double calculate_aggregated_variance_cpp(const VectorXd& eta, const VectorXd& V_t, const VectorXd& V_s, const VectorXd& n_s, double V_ot, double n_t, const VectorXd& C_ot, const MatrixXd& C_cross, double lambda, double mu_ot);
RcppExport SEXP _RoCE_calculate_aggregated_variance_cpp(SEXP etaSEXP, SEXP V_tSEXP, SEXP V_sSEXP, SEXP n_sSEXP, SEXP V_otSEXP, SEXP n_tSEXP, SEXP C_otSEXP, SEXP C_crossSEXP, SEXP lambdaSEXP, SEXP mu_otSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const VectorXd& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_t(V_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_s(V_sSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type n_s(n_sSEXP);
    Rcpp::traits::input_parameter< double >::type V_ot(V_otSEXP);
    Rcpp::traits::input_parameter< double >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type C_ot(C_otSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type C_cross(C_crossSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ot(mu_otSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_aggregated_variance_cpp(eta, V_t, V_s, n_s, V_ot, n_t, C_ot, C_cross, lambda, mu_ot));
    return rcpp_result_gen;
END_RCPP
}
// evaluate_lambda_grid_weights_cpp
NumericVector evaluate_lambda_grid_weights_cpp(const VectorXd& estimates, const VectorXd& V_t, const VectorXd& V_s, const VectorXd& n_s_vec, double V_ot, double n_t, const VectorXd& C_ot, double mu_ot, const MatrixXd& C_cross, const VectorXd& lambda_grid, int max_iter, double tol);
RcppExport SEXP _RoCE_evaluate_lambda_grid_weights_cpp(SEXP estimatesSEXP, SEXP V_tSEXP, SEXP V_sSEXP, SEXP n_s_vecSEXP, SEXP V_otSEXP, SEXP n_tSEXP, SEXP C_otSEXP, SEXP mu_otSEXP, SEXP C_crossSEXP, SEXP lambda_gridSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const VectorXd& >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_t(V_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type V_s(V_sSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type n_s_vec(n_s_vecSEXP);
    Rcpp::traits::input_parameter< double >::type V_ot(V_otSEXP);
    Rcpp::traits::input_parameter< double >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type C_ot(C_otSEXP);
    Rcpp::traits::input_parameter< double >::type mu_ot(mu_otSEXP);
    Rcpp::traits::input_parameter< const MatrixXd& >::type C_cross(C_crossSEXP);
    Rcpp::traits::input_parameter< const VectorXd& >::type lambda_grid(lambda_gridSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_lambda_grid_weights_cpp(estimates, V_t, V_s, n_s_vec, V_ot, n_t, C_ot, mu_ot, C_cross, lambda_grid, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RoCE_nuisance_solver_cpp", (DL_FUNC) &_RoCE_nuisance_solver_cpp, 0},
    {"_RoCE_set_nuisance_solver_cpp", (DL_FUNC) &_RoCE_set_nuisance_solver_cpp, 1},
    {"_RoCE_fit_unified_density_ratio_cpp", (DL_FUNC) &_RoCE_fit_unified_density_ratio_cpp, 15},
    {"_RoCE_fit_initial_density_ratio_cpp", (DL_FUNC) &_RoCE_fit_initial_density_ratio_cpp, 9},
    {"_RoCE_select_lambda_cv_density_ratio_cpp", (DL_FUNC) &_RoCE_select_lambda_cv_density_ratio_cpp, 13},
    {"_RoCE_select_lambda_cv_initial_density_ratio_cpp", (DL_FUNC) &_RoCE_select_lambda_cv_initial_density_ratio_cpp, 11},
    {"_RoCE_select_lambda_cv_calibrated_density_ratio_cpp", (DL_FUNC) &_RoCE_select_lambda_cv_calibrated_density_ratio_cpp, 16},
    {"_RoCE_fit_unified_outcome_cpp", (DL_FUNC) &_RoCE_fit_unified_outcome_cpp, 15},
    {"_RoCE_fit_general_glm_cpp", (DL_FUNC) &_RoCE_fit_general_glm_cpp, 9},
    {"_RoCE_select_lambda_cv_general_refined_outcome_cpp", (DL_FUNC) &_RoCE_select_lambda_cv_general_refined_outcome_cpp, 13},
    {"_RoCE_select_lambda_cv_calibrated_outcome_cpp", (DL_FUNC) &_RoCE_select_lambda_cv_calibrated_outcome_cpp, 15},
    {"_RoCE_calculate_glm_gradient_cpp", (DL_FUNC) &_RoCE_calculate_glm_gradient_cpp, 4},
    {"_RoCE_mean_glm_gradient_cpp", (DL_FUNC) &_RoCE_mean_glm_gradient_cpp, 4},
    {"_RoCE_predict_glm_cpp", (DL_FUNC) &_RoCE_predict_glm_cpp, 4},
    {"_RoCE_calculate_correction_term_cpp", (DL_FUNC) &_RoCE_calculate_correction_term_cpp, 10},
    {"_RoCE_calculate_source_variance_cpp", (DL_FUNC) &_RoCE_calculate_source_variance_cpp, 11},
    {"_RoCE_calculate_target_variance_cpp", (DL_FUNC) &_RoCE_calculate_target_variance_cpp, 5},
    {"_RoCE_calculate_covariance_term_cpp", (DL_FUNC) &_RoCE_calculate_covariance_term_cpp, 2},
    {"_RoCE_optimize_weights_cpp", (DL_FUNC) &_RoCE_optimize_weights_cpp, 13},
    {"_RoCE_calculate_aggregated_estimate_cpp", (DL_FUNC) &_RoCE_calculate_aggregated_estimate_cpp, 3},
    {"_RoCE_calculate_aggregated_variance_cpp", (DL_FUNC) &_RoCE_calculate_aggregated_variance_cpp, 10},
    {"_RoCE_evaluate_lambda_grid_weights_cpp", (DL_FUNC) &_RoCE_evaluate_lambda_grid_weights_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_RoCE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
