# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nuisance_solver_cpp <- function() {
    .Call(`_RoCE_nuisance_solver_cpp`)
}

set_nuisance_solver_cpp <- function(solver) {
    .Call(`_RoCE_set_nuisance_solver_cpp`, solver)
}

fit_unified_density_ratio_cpp <- function(Z_site, A_source, mean_grad_psi, alpha_init, lambda, max_iter, tol, calibrated, M_tau, W_outcome, A_val, family_int, link_int, warm_start, truncate_initial_outcome = TRUE) {
    .Call(`_RoCE_fit_unified_density_ratio_cpp`, Z_site, A_source, mean_grad_psi, alpha_init, lambda, max_iter, tol, calibrated, M_tau, W_outcome, A_val, family_int, link_int, warm_start, truncate_initial_outcome)
}

fit_initial_density_ratio_cpp <- function(Z_site, A_source, mean_phi, lambda, max_iter, tol, A_val, M_tau, warm_start) {
    .Call(`_RoCE_fit_initial_density_ratio_cpp`, Z_site, A_source, mean_phi, lambda, max_iter, tol, A_val, M_tau, warm_start)
}

select_lambda_cv_density_ratio_cpp <- function(Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, A_val, family_int, link_int, cv_fold_id = NULL, use_kkt_certificate = FALSE) {
    .Call(`_RoCE_select_lambda_cv_density_ratio_cpp`, Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, A_val, family_int, link_int, cv_fold_id, use_kkt_certificate)
}

select_lambda_cv_initial_density_ratio_cpp <- function(Z_site, A_source, mean_phi, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, cv_fold_id = NULL, use_kkt_certificate = FALSE) {
    .Call(`_RoCE_select_lambda_cv_initial_density_ratio_cpp`, Z_site, A_source, mean_phi, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, cv_fold_id, use_kkt_certificate)
}

select_lambda_cv_calibrated_density_ratio_cpp <- function(Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, M_tau, W_outcome, A_val, family_int, link_int, cv_fold_id = NULL, truncate_initial_outcome = TRUE, use_kkt_certificate = FALSE) {
    .Call(`_RoCE_select_lambda_cv_calibrated_density_ratio_cpp`, Z_site, A_source, mean_grad_psi, alpha_init, lambda_grid, n_folds, max_iter, tol, M_tau, W_outcome, A_val, family_int, link_int, cv_fold_id, truncate_initial_outcome, use_kkt_certificate)
}

fit_unified_outcome_cpp <- function(W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda, max_iter, tol, A_val, calibrated, M_tau, Z_site, warm_start, use_weight_derivative = FALSE) {
    .Call(`_RoCE_fit_unified_outcome_cpp`, W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda, max_iter, tol, A_val, calibrated, M_tau, Z_site, warm_start, use_weight_derivative)
}

fit_general_glm_cpp <- function(X, Y, weights, family_int, link_int, lambda, max_iter, tol, warm_start) {
    .Call(`_RoCE_fit_general_glm_cpp`, X, Y, weights, family_int, link_int, lambda, max_iter, tol, warm_start)
}

select_lambda_cv_general_refined_outcome_cpp <- function(W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda_grid, n_folds, max_iter, tol, A_val, Z_site, cv_fold_id = NULL) {
    .Call(`_RoCE_select_lambda_cv_general_refined_outcome_cpp`, W_outcome, Y_source, A_source, gamma_s, family_int, link_int, lambda_grid, n_folds, max_iter, tol, A_val, Z_site, cv_fold_id)
}

select_lambda_cv_calibrated_outcome_cpp <- function(W_outcome, Y_source, A_source, gamma_init, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, Z_site, family_int, link_int, cv_fold_id = NULL, use_weight_derivative = FALSE) {
    .Call(`_RoCE_select_lambda_cv_calibrated_outcome_cpp`, W_outcome, Y_source, A_source, gamma_init, lambda_grid, n_folds, max_iter, tol, A_val, M_tau, Z_site, family_int, link_int, cv_fold_id, use_weight_derivative)
}

calculate_glm_gradient_cpp <- function(W_outcome, beta, family_int, link_int) {
    .Call(`_RoCE_calculate_glm_gradient_cpp`, W_outcome, beta, family_int, link_int)
}

mean_glm_gradient_cpp <- function(W_outcome, beta, family_int, link_int) {
    .Call(`_RoCE_mean_glm_gradient_cpp`, W_outcome, beta, family_int, link_int)
}

predict_glm_cpp <- function(W_outcome, beta, family_int, link_int) {
    .Call(`_RoCE_predict_glm_cpp`, W_outcome, beta, family_int, link_int)
}

calculate_correction_term_cpp <- function(Z_site, A_source, Y_source, gamma_s, alpha_ts, W_outcome, M_tau, family_int, link_int, A_val) {
    .Call(`_RoCE_calculate_correction_term_cpp`, Z_site, A_source, Y_source, gamma_s, alpha_ts, W_outcome, M_tau, family_int, link_int, A_val)
}

calculate_source_variance_cpp <- function(Z_site, A_source, Y_source, gamma_s, alpha_ts, delta_ts, W_outcome, M_tau, family_int, link_int, A_val) {
    .Call(`_RoCE_calculate_source_variance_cpp`, Z_site, A_source, Y_source, gamma_s, alpha_ts, delta_ts, W_outcome, M_tau, family_int, link_int, A_val)
}

calculate_target_variance_cpp <- function(target_W_outcome, alpha_ts, M_ts, family_int, link_int) {
    .Call(`_RoCE_calculate_target_variance_cpp`, target_W_outcome, alpha_ts, M_ts, family_int, link_int)
}

calculate_covariance_term_cpp <- function(varphi_ot, zeta_components) {
    .Call(`_RoCE_calculate_covariance_term_cpp`, varphi_ot, zeta_components)
}

optimize_weights_cpp <- function(estimates, V_t, V_s, n_s, V_ot, n_t, C_ot, lambda, mu_ot, max_iter, tol, C_cross, warm_start) {
    .Call(`_RoCE_optimize_weights_cpp`, estimates, V_t, V_s, n_s, V_ot, n_t, C_ot, lambda, mu_ot, max_iter, tol, C_cross, warm_start)
}

calculate_aggregated_estimate_cpp <- function(mu_ot, mu_ts, eta) {
    .Call(`_RoCE_calculate_aggregated_estimate_cpp`, mu_ot, mu_ts, eta)
}

calculate_aggregated_variance_cpp <- function(eta, V_t, V_s, n_s, V_ot, n_t, C_ot, C_cross, lambda, mu_ot) {
    .Call(`_RoCE_calculate_aggregated_variance_cpp`, eta, V_t, V_s, n_s, V_ot, n_t, C_ot, C_cross, lambda, mu_ot)
}

evaluate_lambda_grid_weights_cpp <- function(estimates, V_t, V_s, n_s_vec, V_ot, n_t, C_ot, mu_ot, C_cross, lambda_grid, max_iter, tol) {
    .Call(`_RoCE_evaluate_lambda_grid_weights_cpp`, estimates, V_t, V_s, n_s_vec, V_ot, n_t, C_ot, mu_ot, C_cross, lambda_grid, max_iter, tol)
}
